/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    colors: {
      'navy': '#072146',
      'core-blue': '#004481',
      'core-dark-blue': '#043263',
      'core-light-blue': '#1464A5',
      'medium-blue': '#1973B8',
      'medium-light-blue': '#49A5E6',
      'sky-blue': '#5BBEFF',
      'sky-light-blue': '#D4EDFC',
      'aqua': '#2DCCCD',
      'aqua-dark': '#028484',
      'aqua-medium': '#02A5A5',
      'aqua-light': '#5AC4C4',
      'aqua-white': '#EAF9FA',
      gray: {
        100: '#F4F4F4',
        200: '#E9E9E9',
        300: '#D3D3D3',
        400: '#BDBDBD',
        500: '#666666',
        600: '#121212',
      },
      'red': '#DA3851',
      'red-dark': '#B92A45',
      'red-medium': '#C0475E',
      'red-light': '#E77D8E',
      'red-white': '#F4C3CA',
      'yellow': '#F8CD51',
      'yellow-dark': '#9C6C01',
      'yellow-medium': '#C49735',
      'yellow-light': '#FADE8E',
      'yellow-white': '#FEF5DC',
      'pink': '#F78BE8',
      'pink-dark': '#AD53A1',
      'pink-medium': '#C569B9',
      'pink-light': '#FAB3F0',
      'pink-white': '#FDDCF8',
      'orange': '#F7893B',
      'orange-dark': '#C65302',
      'orange-medium': '#D8732C',
      'orange-light': '#FAB27F',
      'orange-white': '#FDE7D8',
      'sand': '#D8BE75',
      'sand-dark': '#8E7022',
      'sand-medium': '#B79E5E',
      'sand-light': '#E6D5A5',
      'sand-white': '#F3EBD5',
      'green': '#48AE64',
      'green-dark': '#277A3E',
      'green-medium': '#388D4F',
      'green-light': '#88CA9A',
      'green-white': '#D9EFE0',
      'purple': '#8F7AE5',
      'purple-dark': '#6754B8',
      'purple-medium': '#7C6AC7',
      'purple-light': '#B6A8EE',
      'purple-white': '#DDD7F7',
      'white': '#FFFFFF',
    },
    extend: {
      backgroundImage: {
        'mesh-blue': "url('/gradient/blue.png')",
        'mesh-pink': "url('/gradient/pink.png')",
      },
      fontFamily: {
        medium: ['BBVA Benton Sans Medium'],
        book: ['BBVA Benton Sans Book'],
        bold: ['BBVA Benton Sans Bold'],
      },
    },
  },
  content: [
    './pages/**/*.{tsx,ts}',
    './components/**/*.{ts,tsx}',
  ],
  plugins: [],
}
